version: "3"

services:
  app:
    container_name: forum-app

    build:
      context: .
      dockerfile: docker/app/Dockerfile

    restart: unless-stopped

    env_file:
      - .env
    volumes:
      - "./app:/usr/src/app"
    command: [
      "gunicorn", "core.wsgi:application",
      "--bind", "0.0.0.0:8000",
    ]

  nginx:
    container_name: nginx

    build:
      context: docker/nginx
      dockerfile: Dockerfile

    volumes:
      - "./data/static:/usr/src/app/static"
      - "./data/media:/usr/src/app/media"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
